# # # Makefile de Lista

# # # Variables
# # CC = g++
# # JOSH = -g
# # EJECUTABLE = main

# # # Programa Principal
# # all: lista.h nodo.h
# # 	$(CC) $(JOSH) nodo.h lista.h main.cpp -o $(EJECUTABLE)

# # # Librerías



# # lista.h: lista.h 
# # 	$(CC) $(JOSH) -c lista.h
# # nodo.h: nodo.h 
# # 	$(CC) $(JOSH) -c nodo.h
	
# # # Borrar los Archivos Objeto y el Ejecutable
# # clean:
# # 	rm -rf *.o $(EJECUTABLE) 
# # Makefile de Lista

# # Variables
# # Makefile for List

# # Variables
# COMPILER = g++
# FLAGS = -g
# EXECUTABLE = main

# # Main Program
# all: list.h node.h
# 	$(COMPILER) $(FLAGS) node.h list.h main.cpp -o $(EXECUTABLE)

# # Libraries



# # list.h: list.h 
# # 	$(COMPILER) $(FLAGS) -c list.h
# # node.h: node.h 
# # 	$(COMPILER) $(FLAGS) -c node.h
	
# # Clean Object Files and Executable
# clean:
# 	rm -rf *.o $(EXECUTABLE) 
